### PR TITLE
React Calculator

### PR DESCRIPTION
**Pull request by GraceOyiza**
Project setup
- Initialize  GitHub
- Install prop-types and big.js
- Push to Heroku

### CODE REVIEW

**Review by trekab — COMMENTED** [review]
### Invalid! :stop_sign: 
Hi @GraceOyiza! Unfortunately, I have to invalidate your PR because you didn't set up [linting](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-). Please check out the [Professional repo guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/), make the necessary changes, and submit another code review request.

__[Treasure Kabareebe](https://trekab.github.io)__

**Comment by GraceOyiza** [comment]
- Lint added

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @GraceOyiza! Your setup looks good but it appears that you forgot to share your live version link in your readme. Please update your readme using [this template](https://github.com/microverseinc/readme-template) and share your live demo link.

_Please make the necessary changes and submit another code review request._
__[Treasure Kabareebe](https://trekab.github.io)__

**Comment by GraceOyiza** [comment]
- Update readme file.
- Add live link.

**Review by uche-inyama — APPROVED** [review]
## Approved :heavy_check_mark: 

### Hi Grace :slightly_smiling_face: 

Go on with the next milestone.

### Have a great day :man_technologist: 

#### ``` Uchechukwu Henry Inyama ```

**Pull request merged**
