### PR TITLE
Milestone five

### PR DESCRIPTION
**Pull request by GraceOyiza**
- Change app to a stateful parent component
- Implement handleDisplay
- Implement handleClick
- Use onClick event

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @GraceOyiza**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] Make sure to add a division by Zero error exception. Right now the app crashes if you divide anything by zero. 
- [ ] The original app requirements had a +/- button instead of the X² button. make sure to stick to those requirements. 


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by GraceOyiza** [comment]
- Use the required requirement.
- Fix the division of zero error

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️ 
@GraceOyiza Nice job for trying to implement suggested changes by the previous Code reviewer, however, changes are required:
### highlights
Make sure to add a division by Zero error exception. Right now the app crashes if you divide anything by zero 👍🏻 
### improve
The original app requirements had a +/- button that should be in place of the X² button. kindly check the project requirements and fix them.
## [ Optional]
kindly update your app to deployment with the latest version


### once specific changes are made kindly request for another review

**Comment by GraceOyiza** [comment]
- Replace 'X²' to '+/-'

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi Grace :slightly_smiling_face: 

We are almost through, but the **+/-** button on the calculator isn't working.

kindly fix that, then request for another code review.

### Have a great day :wave: 

#### ``` Uchechukwu Henry Inyama ```

**Comment by GraceOyiza** [comment]
- Fix +/- button.

**Review by voscarmv — APPROVED** [review]
# Project status: Approved 💯 ✨ 😎 👍 
### You may merge this branch and move forward ⛙🛣️ 

- I'm approving your project to help accelerate your completion of the 1.0 program. However, please fix the +/- button before merging.

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
